
id = "Kaiawoo.SkyboxFuckery"
name = "Skybox Fuckery"
description = "Why am I doing this."
version = "1.0.0"
homepage = "https://github.com/NotNite/WebfishingSampleMod"
author = "Kaiawoo"

icon = "icon.png"
readme = "README.md"

[project]
csharp = "./WebfishingSampleMod/WebfishingSampleMod.csproj"
godot = "./project/project.godot"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.14"
